version: "3"
networks:
  mcs-portal:
    name: mcs-portal
services:
  neo4j:
    build:
      context: .
      dockerfile: neo4j/Dockerfile
    container_name: mcs-portal-neo4j
    networks:
      - mcs-portal
    ports:
      - 7474:7474 # HTTP
      - 7687:7687 # Bolt
    restart: unless-stopped
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-import:/var/lib/neo4j/import
      - neo4j-plugins:/plugins
volumes:
  neo4j-data:
  neo4j-import:
  neo4j-logs:
  neo4j-plugins:
