version: "3"
services:
  mowgli-gui-app:
    build:
      context: ..
      dockerfile: gui/Dockerfile
    container_name: mowgli-gui-app
#  mowgli-gui-gui:
#    build:
#      context: ./gui
#    container_name: mowgli-gui-gui
#    ports:
#      - 127.0.0.1:8081:80
  neo4j:
    container_name: neo4j
    image: neo4j:3.5.3
    environment:
      NEO4J_AUTH: neo4j/nC1aB4mji623s2Zs
    ports:
      - 127.0.0.1:7474:7474 # HTTP
      - 127.0.0.1:7687:7687 # Bolt
    volumes:
      - ./data/neo4j/data:/data
      - ./data/neo4j/logs:/logs
      - ./data/neo4j/import:/var/lib/neo4j/import
      - ./data/neo4j/plugins:/plugins

