version: "3.5"
networks:
  mcs:
    name: mcs
services:
  benchmark-app:
    build:
      context: .
      dockerfile: app/benchmark/Dockerfile
    container_name: mcs-benchmark-app
    image: tetherlessworld/mcs-benchmark-app
    networks:
      - mcs
    ports:
      - 127.0.0.1:8080:80
    restart: unless-stopped
    volumes:
      - ./data/kg:/data/kg
  kg-app:
    build:
      context: .
      dockerfile: app/kg/Dockerfile
    container_name: mcs-kg-app
    image: tetherlessworld/mcs-kg-app
    networks:
      - mcs
    ports:
      - 127.0.0.1:8080:80
    restart: unless-stopped
    volumes:
      - ./data/kg:/data
  neo4j:
    container_name: mcs-neo4j
    environment:
      NEO4J_AUTH: "neo4j/nC1aB4mji623s2Zs"
      NEO4JLABS_PLUGINS: "[\"apoc\",\"graph-data-science\"]"
      NEO4J_dbms_memory_pagecache_size: "8G"
      NEO4J_dbms_memory_heap_max__size: "8G"
    image: library/neo4j:4.0.4
    networks:
      - mcs
    ports:
      - 7474:7474 # HTTP
      - 7687:7687 # Bolt
    restart: unless-stopped
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-import:/var/lib/neo4j/import
      - neo4j-plugins:/plugins
  postgres:
    container_name: mcs-postgres
    environment:
      POSTGRES_USER: "mcs"
      POSTGRES_PASSWORD: "7EAdu7jJvZNxxrNZ"
      POSTGRES_DB: "kg"
    image: library/postgres:12.4
    networks:
      - mcs
    ports:
      - 127.0.0.1:5432:5432
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  neo4j-data:
  neo4j-import:
  neo4j-logs:
  neo4j-plugins:
  postgres-data:
