version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcs-portal-app
    restart: unless-stopped
    volumes:
      - ./data:/app/data
  gui:
    build:
      # Use the same context to share a .dockerignore
      context: .
      dockerfile: gui/Dockerfile
    container_name: mcs-portal-gui
    depends_on:
      - app
    ports:
      - 127.0.0.1:8080:80
    restart: unless-stopped
  neo4j:
    build:
      context: .
      dockerfile: neo4j/Dockerfile
    container_name: mcs-portal-neo4j
    ports:
      - 7474:7474 # HTTP
      - 7687:7687 # Bolt
    restart: unless-stopped
    volumes:
      - mcs-portal-neo4j-data:/data
      - mcs-portal-neo4j-logs:/logs
      - mcs-portal-neo4j-import:/var/lib/neo4j/import
      - mcs-portal-neo4j-plugins:/plugins
volumes:
  mcs-portal-neo4j-data:
  mcs-portal-neo4j-import:
  mcs-portal-neo4j-logs:
  mcs-portal-neo4j-plugins:
