version: "3.5"
networks:
  mcs:
    name: mcs
services:
  benchmark-app:
    build:
      context: .
      dockerfile: app/benchmark/Dockerfile
    container_name: mcs-benchmark-app
    image: tetherlessworld/mcs-benchmark-app
    networks:
      - mcs
    ports:
      - 127.0.0.1:8080:80
    restart: unless-stopped
    volumes:
      - ./data/kg:/data/kg
  kg-app:
    build:
      context: .
      dockerfile: app/kg/Dockerfile
    container_name: mcs-kg-app
    image: tetherlessworld/mcs-kg-app
    networks:
      - mcs
    ports:
      - 127.0.0.1:8080:80
    restart: unless-stopped
    volumes:
      - ./data/kg:/data
  kg-app-isi:
    build:
      args:
        BASE_HREF: "/mcs-cskg/"
      context: .
      dockerfile: app/kg/Dockerfile
    container_name: mcs-kg-app
    environment:
      BASE_HREF: "/mcs-cskg/"
    image: tetherlessworld/mcs-kg-app
    networks:
      - mcs
    ports:
      - 0.0.0.0:8383:80
    restart: unless-stopped
    volumes:
      - ./data/kg:/data
  nginx-isi:
    build:
      context: nginx-isi
      dockerfile: Dockerfile
    container_name: mcs-nginx-isi
    networks:
      - mcs
    ports:
      - 127.0.0.1:8081:80
    restart: unless-stopped
  neo4j:
    container_name: mcs-neo4j
    environment:
      NEO4J_AUTH: "neo4j/nC1aB4mji623s2Zs"
      NEO4JLABS_PLUGINS: "[\"apoc\",\"graph-data-science\"]"
      NEO4J_dbms_memory_pagecache_size: "8G"
      NEO4J_dbms_memory_heap_max__size: "8G"
    image: neo4j:4.0.4
    networks:
      - mcs
    ports:
      - 7474:7474 # HTTP
      - 7687:7687 # Bolt
    restart: unless-stopped
    volumes:
      - neo4j-data:/data
volumes:
  neo4j-data:
