version: 2.1
jobs:
  benchmark-app-docker:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build
          command: |
            docker-compose build benchmark-app neo4j
      - run:
          name: Run
          background: true
          command: |
            docker-compose up --abort-on-container-exit benchmark-app neo4j
      - run:
          name: Wait for the server to start
          command: |
            sleep 90
            docker exec mcs-benchmark-app curl --retry 10 --retry-connrefused -s http://localhost
      - run:
          name: Push to DockerHub
          command: |
            docker login -u $DOCKER_ID -p $DOCKER_PASSWORD && docker-compose push benchmark-app
  benchmark-app-scala:
    docker:
      - image: circleci/openjdk:11
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - restore_cache:
          key: sbt-cache-v1
      - run:
          name: Build and test
          command: |
            cp -p -R /tmp/workspace/dist/gui/benchmark app/benchmark/public
            sbt "project benchmarkLib" test "project benchmarkApp" test playUpdateSecret dist
            mkdir -p test-reports/app
            mkdir -p test-reports/lib
            cp -p -R app/benchmark/target/test-reports test-reports/app/benchmark
            cp -p -R lib/scala/benchmark/target/test-reports test-reports/lib/benchmark
            mkdir -p ~/dist/app
            cd app/benchmark/target/universal && unzip -qq mcs-benchmark-app*.zip && rm mcs-benchmark-app*.zip && mv mcs-benchmark-app-*-SNAPSHOT ~/dist/app/benchmark
      - store_test_results:
          path: test-reports
      - persist_to_workspace:
          root: ~/
          paths:
            - dist/app
      - save_cache:
          key: sbt-cache-v1
          paths:
            - "~/.ivy2/cache"
            - "~/.m2"
            - "~/.sbt"
  kg-app-docker:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build
          command: |
            docker-compose build kg-app neo4j
      - run:
          name: Run
          background: true
          command: |
            docker-compose up --abort-on-container-exit kg-app neo4j
      - run:
          name: Wait for the server to start
          command: |
            sleep 90
            docker exec mcs-kg-app curl --retry 10 --retry-connrefused -s http://localhost
      - run:
          name: Push to DockerHub
          command: |
            docker login -u $DOCKER_ID -p $DOCKER_PASSWORD && docker-compose push kg-app
  kg-app-scala:
    docker:
      - image: circleci/openjdk:11
      - image: neo4j:4.0.4
        name: mcs-neo4j
        environment:
          NEO4J_AUTH: neo4j/nC1aB4mji623s2Zs
          NEO4JLABS_PLUGINS: '["apoc","graph-data-science"]'
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - restore_cache:
          key: sbt-cache-v1
      - run:
          name: Build and test
          command: |
            cp -p -R /tmp/workspace/dist/gui/kg app/kg/public
            sbt "project kgLib" test "project kgApp" test playUpdateSecret dist
            mkdir -p test-reports/app
            mkdir -p test-reports/lib
            cp -p -R app/kg/target/test-reports test-reports/app/kg
            cp -p -R lib/scala/kg/target/test-reports test-reports/lib/kg
            mkdir -p ~/dist/app
            cd app/kg/target/universal && unzip -qq mcs-kg-app*.zip && rm mcs-kg-app*.zip && mv mcs-kg-app-*-SNAPSHOT ~/dist/app/kg
      - store_test_results:
          path: test-reports
      - persist_to_workspace:
          root: ~/
          paths:
            - dist/app
      - save_cache:
          key: sbt-cache-v1
          paths:
            - "~/.ivy2/cache"
            - "~/.m2"
            - "~/.sbt"
  ts:
    working_directory: ~/project
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: ts-dependency-cache-v2-{{ checksum "gui/package.json" }}
      - run:
          name: Install dependencies
          command: |
            cd gui
            npm install
      - save_cache:
          key: ts-dependency-cache-v2-{{ checksum "gui/package.json" }}
          paths:
            - gui/node_modules
      - run:
          name: Build
          command: |
            cd gui
            npm run build-benchmark
            npm run build-kg
            mkdir -p ~/dist
            mv dist ~/dist/gui
      - persist_to_workspace:
          root: ~/
          paths:
            - dist/gui
orbs:
  cypress: cypress-io/cypress@1
  slack: circleci/slack@3.4.2
workflows:
  version: 2
  benchmark-app:
    jobs:
      - benchmark-app-docker:
          filters:
            branches:
              only: master
          post-steps:
            - slack/status
      - benchmark-app-scala:
          requires:
            - ts
          post-steps:
            - slack/status
      - ts:
          post-steps:
            - slack/status:
                fail_only: true
  kg-app:
    jobs:
      - cypress/install:
          cache-key: 'npm-packages-v2-{{ arch }}-{{ checksum "integration/package.json" }}'
          name: cypress/install-kg-app
          requires:
            - kg-app-scala
          working_directory: integration
          post-steps:
            - slack/status:
                fail_only: true
      - cypress/run:
          attach-workspace: true
          cache-key: 'npm-packages-v2-{{ arch }}-{{ checksum "integration/package.json" }}'
          name: "cypress/run-kg-app"
          post-steps:
            - store_test_results:
                path: integration/results
            - store_artifacts:
                path: integration/cypress/screenshots
            - store_artifacts:
                path: integration/cypress/videos
            - slack/status
          requires:
            - cypress/install-kg-app
          spec: "cypress/integration/kg/*.spec.ts"
          start: |
            pwd
            cp ~/project/.circleci/cypress.json .
            apt-get update && apt-get install -y default-jre
            cd ~/dist/app/kg
            bin/mcs-kg-app -DkgStore=test
          wait-on: "http-get://localhost:9000/index.html"
          working_directory: integration
      - kg-app-docker:
          filters:
            branches:
              only: master
          post-steps:
            - slack/status
      - kg-app-scala:
          requires:
            - ts
          post-steps:
            - slack/status:
                fail_only: true
      - ts:
          post-steps:
            - slack/status:
                fail_only: true
