schema: http://localhost:9000/api/graphql
documents: ./src/benchmark/api/queries/*.graphql
overwrite: true
generates:
  ./src/benchmark/api/graphqlFragmentTypes.json:
    plugins:
      - fragment-matcher
